services:
  rag-pipeline-service:
    container_name: rag-pipeline-container
    build: .
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - OPENSEARCH_ENDPOINT=https://opensearch-rag-pipeline:9200
    ports:
      - "80:8501"
    depends_on:
      - opensearch-rag-pipeline

  opensearch-rag-pipeline:
    container_name: opensearch-rag-pipeline
    image: opensearchproject/opensearch:2
    environment:
      - cluster.name=rag-pipeline-cluster
      - node.name=rag-pipeline-node1
      - discovery.seed_hosts=rag-pipeline-node1
      - cluster.initial_cluster_manager_nodes=rag-pipeline-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}  # USERNAME: admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-rag-pipeline:9200"]
    depends_on:
      - opensearch-rag-pipeline